# Generated by Django 2.2.24 on 2022-08-26 12:17

from django.db import migrations


def mark_new_building_by_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220826_1500'),
    ]

    operations = [
        migrations.RunPython(mark_new_building_by_year)
    ]
