# Generated by Django 2.2.24 on 2022-08-27 14:14

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner_name = flat.owner
        owner_pure_phone = flat.owner_pure_phone
        owner, created = Owner.objects.get_or_create(
            name=owner_name,
            normalized_phone=owner_pure_phone,
            defaults={'phone_number': owner_pure_phone},
        )
        owner.flats.add(flat)


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners, move_backward)
    ]
