# Generated by Django 2.2.24 on 2022-08-27 16:57

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            normalized_phone=flat.owner_pure_phone,
            defaults={
                'phone_number': flat.owner_pure_phone,
            },
        )


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220827_1956'),
    ]

    operations = [
        migrations.RunPython(create_owners, move_backward)
    ]
